#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello world" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "/listen \[::]:80 default_server;/a\	rewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=mTEros927Ow permanent;" /etc/nginx/sites-available/default
sed -i "/listen \[::]:80 default_server;/a\	error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i '/http {/a\\n\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

service nginx restart
